# -------------------------
# Nodes
# -------------------------

mgi gene:
  represented_as: node
  input_label: gene
  is_a: gene
  properties:
    symbol: str

ensembl gene:
  represented_as: node
  input_label: ensembl_gene
  is_a: gene
  properties:
    symbol: str

mp phenotype:
  represented_as: node
  input_label: phenotype
  is_a: phenotypic feature
  properties:
    name: str

tissue:
  represented_as: node
  input_label: tissue
  is_a: anatomical entity
  properties:
    name: str

protein:
  represented_as: node
  input_label: protein
  is_a: protein
  properties: {}

# -------------------------
# Edges
# -------------------------

gene has phenotype:
  represented_as: edge
  input_label: gene_has_phenotype
  is_a: association
  source: mgi gene
  target: mp phenotype
  properties:
    pmid: str
    genotype_id: str
    background: str
    allelic_composition: str
    allele_symbol: str

has expression:
  represented_as: edge
  input_label: has_expression
  is_a: association
  source: ensembl gene
  target: tissue
  properties:
    tpm: float
    experiment_id: str

protein interacts with protein:
  represented_as: edge
  input_label: protein_interacts_with_protein
  is_a: pairwise molecular interaction
  source: protein
  target: protein
  properties:
    combined_score: int
